### ISSUE TITLE
Package with DLC = 0 not recognized

### ISSUE THREAD

**Issue by mansk789** [adafruit/arduino-CAN#7]
- Arduino board:  Adafruit Feather M4 CAN

- Arduino IDE version (found in Arduino -> About Arduino menu): 1.8.13

- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too): 
 1.) Download Example "CANReceiverCallback.ino" 
 2.) Send an CAN-Packet (any) with DLC 0
 3.) CAN-Receiver does not receive it!!!

Package with DLC0 might be used for heartbeat or similar...

**Comment by jostlowe** [comment]
Same issue here. Would love to see the library work for packets with DLC = 0

**Comment by Wetmelon** [comment]
`onInterrupt()` leads to `handleInterrupt()` which leads to `while(int i = parsePacket())`.  `parsePacket()` returns the `rxDlc`.  So if `rxDlc == 0` then:

1. `_rxLength = 0` and `_rxIndex = 0`
2. The `while` never executes, which means the `onReceive` callback is never actually called.
3.  In `read()`, `if(!available())` will be evalulated to `true` because `(rxLength - rxIndex) == 0`, and we immediately return `-1`.

Looks to me like `rxDlc == 0` and `rxRtr` messages won't work across any of these devices.

I'll try to put together a PR.

**Comment by caternuson** [comment]
This library is being deprecated. Please try with the new library here:
https://github.com/adafruit/Adafruit_CAN
If the issue still shows, please open a new issue in that library repo.
